project:
  type: book
  output-dir: ./docs
  resources:
    - "assets"
  render:
    - "index.qmd"
    - "modules/Tech_Fundemental.qmd"

book:
  title: "DE Roadmap"
  author:
    name: "Behzad Valipour Sh."
    url: https://behzad-valipour.netlify.app
  date: today
  cover-image: assets/logos/logo.png
  favicon: assets/logos/logo.png
  repo-url: https://github.com/behzad89/Data_Engineeing_Road_Map
  repo-branch: main
  page-footer:
    center: |
      Author:[[Behzad Valipour Sh.]{.green}](https://behzad-valipour.netlify.app), Senior Software Engineer & team leader at [[Imago]{.blue}](https://imago.ac.uk) project.


  chapters: 
    - "index.qmd"
    - "modules/Tech_Fundemental.qmd"
number-sections: false

format:
  html:
    theme:
      - cosmo
      - assets/styles.scss
    toc: false
