project:
  type: book
  output-dir: ./docs
  resources:
    - "assets"
  render:
    - "index.qmd"
    - "modules/01.Tech_Fundemental.qmd"
    - "modules/012.OSI7_layers.qmd"
    - "modules/100.Tips_Tricks.qmd"
    - "modules/101.GCP.qmd"
    - "modules/013.Other_Networking.qmd"
book:
  title: "DE Roadmap"
  author:
    name: "Behzad Valipour Sh."
    url: https://behzad-valipour.netlify.app
  date: today
  cover-image: assets/logos/logo.png
  favicon: assets/logos/logo.png
  repo-url: https://github.com/behzad89/Data_Engineeing_Road_Map
  repo-branch: main
  page-footer:
    center: |
      Author:[[Behzad Valipour Sh.]{.green}](https://behzad-valipour.netlify.app), Senior Software Engineer & team leader at [[Imago]{.blue}](https://imago.ac.uk) project.


  chapters:
    - "index.qmd"
    - part: "modules/01.Tech_Fundemental.qmd"
      chapters:
        - "modules/012.OSI7_layers.qmd"
        - "modules/013.Other_Networking.qmd"

    - part: "modules/100.Tips_Tricks.qmd"
      chapters:
        - "modules/101.GCP.qmd"
        
number-sections: false

format:
  html:
    theme:
      - cosmo
      - assets/styles.scss
    toc: false